### ISSUE TITLE
Remove transform tests failing across 3 engines?

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop-2022#100]
** Test List **

css/css-transforms/backface-visibility-hidden-004.tentative.html
css/css-transforms/backface-visibility-hidden-005.tentative.html
css/css-transforms/backface-visibility-hidden-animated-002.html

** Rationale **

The two first tests are tentative, so it may well be possible they are not up to date.

Not sure about the 3rd one.

**Comment by jgraham** [comment]
Ideally rather than just removing them we'd figure out what the underlying issue is; if the tests are wrong we should replace them with correct tests, if the spec is wrong we should update it. If implementations are failing in different ways we may still have an interop problem here that shouldn't be brushed under the carpet.

**Comment by nt1m** [comment]
@jgraham I'm no transforms expert, but all 3 tests fail in the same way in all 3 browser engines, they display as blank rather than as a green square.

**Comment by dbaron** [comment]
So `backface-visibility` interop is, right now, horrible.  The spec basically isn't clear enough to say what to do, particularly with regards to grouping (i.e., when something becomes hidden due to backface-visibility: hidden, which descendants does this apply to?).  This is very closely related to the question of what grouping effects (such as stacking context, grouping property, containing block for absolute/fixed) `backface-visibility:hidden` causes.  There's some discussion of this in w3c/csswg-drafts#918 and elsewhere but I don't think there's a single place that summarizes the whole mess.

I've been hoping to take some time to improve interoperability here -- it's the next major thing I'd like to look at as editor of the transforms spec, as [I mentioned](https://www.w3.org/blog/CSS/2021/11/09/css-transforms-level-2-updated/) in the last spec update.

I'm not sure whether this issue is requesting:
 * deletion of the tests from web-platform-tests, or
 * making the tests not count towards interop-2022.

I'm fine with the latter (given that we don't yet have a good enough spec to yield interop), but I'd prefer not to delete tests right now, since they help track some of the issues that we need to solve.  I'd be ok with marking additional tests as tentative if that makes sense, and I'm also fine with not counting those tests towards interop-2022.

(I actually do honestly expect to get to this before the end of this year, since I think it's currently the second large task on my todo list.)

**Comment by jgraham** [comment]
I'm pretty sure the proposal is just to remove them from interop-2022, not from the repo. And by the sounds of it that should be fine (we should probably have some rule requiring extra justification for including tentative tests so that we can look up the original motivation for including the test if this kind of question arises).

**Comment by nt1m** [comment]
Yes I'm suggesting to remove them from interop-2022 only.

**Comment by nt1m** [comment]
Seems like there's general consensus here, so I went ahead and did it

**Comment by foolip** [comment]
Huh, I thought I did a few passes looking for tentative tests, but suppose I didn't really...

This issue was on the agenda of https://github.com/web-platform-tests/interop-2022/issues/103 today and that was a chance for folks to voice concerns. There were none, so let's stick with dropping the tests. (Done in https://github.com/web-platform-tests/wpt-metadata/pull/2926.)
