### ISSUE TITLE
AVIF Support

### ISSUE THREAD

**Issue by una** [web-platform-tests/interop-2022#22]
**Description**
AVIF is a new image format derived from the keyframes of AV1 video. [More about AVIF](https://jakearchibald.com/2020/avif-has-landed/)

**Specification**
[AV1-AVIF](https://github.com/AOMediaCodec/av1-avif)

**Tests**
[Test Files](https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles)

**Rationale**
AVIF provides significant image size savings. With web performance being a key concern for developers, and images taking up the bulk of downloaded web content size, a more efficient file format helps significantly.

**Comment by foolip** [comment]
https://caniuse.com/avif says AVIF is supported in Chrome and Firefox.

https://wpt.fyi/results/apng is an example of image format tests in WPT, but this isn't very common. There are not tests that I know of for JPEG, PNG or WebP specifically, and I can't find any tests for AVIF. @una do you know if https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles is being used in automated browser testing? Would you propose bringing thorough AVIF testing into WPT, or just a simple "does it work at all" test?

On the rationale, what do we know about web developer demand for new image formats? While AVIF was [mentioned twice](https://docs.google.com/spreadsheets/d/1W1scqBvz6xRERPGOCm_29cc71U9CJiIlfeNNyys-27M/edit#gid=1399297592) in State of CSS 2021, that survey isn't really where I'd expect to find strong signals about it, since image formats isn't clearly in scope, and might not be mentioned even if it is a big problem.

**Comment by foolip** [comment]
I've learned from @dalecurtis that there are a few tests for AVIF in https://wpt.fyi/results/webcodecs/image-decoder.https.any.html.

Looking for other *.avif files in WPT and tests that use them, I found one more, a manual test:
https://wpt.live/html/canvas/element/manual/wide-gamut-canvas/canvas-createImageBitmap-e_srgb.html

Basic tests for AVIF in `<img>` would be needed here, of course.

**Comment by annevk** [comment]
It might be problematic to include tests that depend on another feature, e.g., `ImageDecoder`. (Or maybe that's what you meant.)

**Comment by foolip** [comment]
@annevk yes, I think we would need basic tests for AVIF in `<img>` which don't involve `ImageDecoder`, and if `ImageDecoder` won't ship before AVIF in all browsers then we shouldn't have any tests that depend on `ImageDecoder`.

**Comment by foolip** [comment]
This proposal wasn't fully resolved in yesterday's meeting, see https://github.com/web-platform-tests/interop-2022/issues/39#issuecomment-991001758.

There may be an intersection in what Google and Mozilla would like to support in 2022. However, that doesn't guarantee inclusion given Microsoft's comments about hardware support. We need to revisit this in the next meeting.

@scottlow @dlibby- can you clarify your position on this? *If* Google and Mozilla identify a common subset, would you like to include it in the metric and continue to investigate, or exclude and continue to investigate? (If it's the latter, then we don't need to spend more time here.)

**Comment by scottlow** [comment]
@foolip, I chatted with our media team this afternoon. Their preference is for this to be excluded while we all continue to investigate.

**Comment by foolip** [comment]
Thanks @scottlow, that makes the discussion in today's meeting a lot simpler!
