### ISSUE TITLE
Retrospective on process and launch

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop-2022#68]
Interop 2022 launched on March 3, 2022, with [a lot of buzz](https://docs.google.com/document/d/1iRfw36aoADk6ctz3Lx6fV0J8UF1hY0hwSBeQjW7xyEI/edit?usp=sharing) and excitement.

While it's still fresh in memory, I think it would be good to look back at the whole process and launch, and record learnings for Interop 2023. Some probing questions:
- What worked well and not so good with our proposal process?
- What additional research or data could have helped?
- How did https://github.com/web-platform-tests/interop-2022/issues/38 work?
- How did the launch itself go?

**Comment by foolip** [comment]
Discussed in https://github.com/web-platform-tests/interop-2022/issues/69

Brian: It's a bit early to say if it worked well or not.

James: For gather positions, hopefully next time we'll have a clearer shared understanding to avoid last minute changes. But big picture nominations and consensus worked well.

Philip: Typography and Encodings. [to flesh out later]

Simon: I'd like a clearer plan and timeline, it was a bit last minute for us.

Brian: It took time to sort out things we'd never done before and we had time pressure, and then world events.

**Comment by gsnedders** [comment]
FWIW: I started writing something longer a while back, but I never finished it. I probably should finish it.

**Comment by foolip** [comment]
@gsnedders I also have a half finished thing. Maybe we can just post our unfinished thoughts? 😀

**Comment by foolip** [comment]
Here are my initial thoughts on how [Interop 2022 positions](https://docs.google.com/spreadsheets/d/1SQF81pf5hxFE9dMZcJGXE2RNmb7AjFHg6mnkf9KOEC0/edit#gid=4939874) worked.

Overall, I'm very happy with the outcome, for example Subgrid, Cascade Layers, and Forms are focus areas that I think will be noticed by web developers, and the Support/Oppose/Neutral method of establishing consensus worked well here.

However, I think the way we did proposals and sub-proposals turned out suboptimal since we ultimately had to consider each sub-proposal individually and then group things back into focus areas afterwards.

With the Typography and Encodings proposal (originally just Typography) I think good features were included, but @drott and I considered color fonts to be the strongest part of the overall proposal. Here are the positions for the sub-proposals that let to that being excluded:

Sub-proposal | Consensus | Apple | Bocoup | Google | Igalia | Microsoft | Mozilla
-- | -- | -- | -- | -- | -- | -- | --
font-variant-alternates + font-variant-position | Include | Support | Support | Neutral | Neutral | Neutral | Support
IC unit (CJK focused) | Include | Support | Support | Neutral | Support | Neutral | Support
hanging punctuation (JP focused) | Exclude | Support | Support | Neutral | Support | Neutral | Oppose
Initial Letter | Exclude | Neutral | Support | Neutral | Neutral | Neutral | Neutral
Color fonts | Exclude | Support | Support | Support | Neutral | Neutral | Oppose
Segment Break Transformation rules | Exclude | Oppose | Investigate | See comment | Neutral | Neutral | Support
CJK text encoding | Include | Support | Neutral | Neutral | Neutral | Neutral | Support

That is fair of course, that's the process we all agreed to. But from Google's point of view, the most compelling part of the focus area was missing.

A few thoughts on changes we could make for Interop 2023:
- Drop the notion of proposals and sub-proposals, since it only makes sense to have positions on the more specific (sub-proposals)
- Conditional support, if someone feels certain proposals only make sense together
- A second round of positions on the grouped focus areas, to give the option to exclude at least the things that nobody is happy with (I don't that's likely, but it's possible per our process)

In addition to the procedural, we should also consider ways of just continuing the conversation, to resolve things by mutual consensus and not by following predefined rules. We were quite light on the formal rules for Interop 2022, and I think that was a strength.

**Comment by gsnedders** [comment]
> While it's still fresh in memory, I think it would be good to look back at the whole process and launch, and record learnings for Interop 2023. Some probing questions:
> 
> * What worked well and not so good with our proposal process?

I think it's worthwhile stepping even further back than that; one thing that was clear to me was we didn't actually have a good grasp on what exactly the goals were, and what the inclusion criteria was. AIUI, the goal with Interop 2021 had been to target known developer pain-points, both in terms of browser incompatibilities and fulfilling feature requests. Some of the challenge with some of the proposal discussions, far as I can tell, is a lack of agreement about the underlying goals of the project even were. It's very hard to evaluate a proposal when you haven't agreed what the goal of the proposals even is.

If we took that statement as the statement of the goal, then we can evaluate proposals against that, potentially with a set of guided questions like:

1. Do you believe working on this feature resolves a known developer pain-point?
2. Do you believe the specification and the tests are sufficient to resolve that pain-point?
3. Do you believe it to be a sufficiently major pain-point to fit into a shortlist for the upcoming year?

These are questions where we can have pretty concrete discussions about. And that's before we get into more nebulous questions about whether or not we allow browsers to oppose inclusion of certain features for unspecified reasons. We can even include such things as part of the proposal template.

Otherwise, the big part of chaos was down to the proposal v. sub-proposal "issue" as discussed by @foolip [above](https://github.com/web-platform-tests/interop-2022/issues/68#issuecomment-1081563621); I think practically trying to do anything with explicit grouping until we know what's actually _in_ is probably not overly worthwhile, and that the right thing to do is to first go through individual proposals (which can actually be evaluated v. the above questions, versus many of the discussions we had internally which were "this is incredibly undefined what this [huge area] is, and our views depend on what is actually intended to be included").

So yeah, my concrete suggestion there is to evaluate things at a meaningful level, and then come up with some proposed grouping—acknowledging we may either need to fudge it somehow or drop certain proposals.

> * What additional research or data could have helped?

I don't think that's answerable without actually defining the goals of the project more clearly.

> * How did [Spreadsheet for tallying positions #38](https://github.com/web-platform-tests/interop-2022/issues/38) work?

I think it was mostly okay; some of the challenges were in the definition of "investigate", and what this meant in terms of any real commitment to move forward with anything.

> * How did the launch itself go?

Aside from [the unfortunate delay](https://en.wikipedia.org/wiki/2022_Russian_invasion_of_Ukraine), I think this went relatively well, though perhaps more time to allow for cross/internal reviews of posts would've been good?

**Comment by robnyman** [comment]
> Do you believe working on this feature resolves a known developer pain-point?
> Do you believe the specification and the tests are sufficient to resolve that pain-point?
> Do you believe it to be a sufficiently major pain-point to fit into a shortlist for the upcoming year?

@gsnedders I like the questions!

There's probably some room in there as well for how useful and used that area is, e.g. there are pain points but for features not much used by the broader developer audience (and likely never will be either, even if the pain points have been addressed).

**Comment by foolip** [comment]
I agree that we shouldn't use the proposal/sub-proposal structure again, that created some unnecessary problems. Doing away with it does seem to necessitate a second decision step after the positions, however, as @gsnedders is getting at here:

> So yeah, my concrete suggestion there is to evaluate things at a meaningful level, and then come up with some proposed grouping—acknowledging we may either need to fudge it somehow or drop certain proposals.

I think we could do this in a group discussion without too much trouble, and maybe that would be enough. I would like to avoid adding a second step in the style of "now everyone feel free to veto anything, no questions asked", because that might nudge us all in the direction of being less careful in the first review/positions step, and creating frustrating vetos in the second step, souring the effort.

**Comment by foolip** [comment]
@gsnedders when it comes to alignment on goals, one practical thing we could do is to write down some principles for the effort, things that we are already largely aligned on. And I think questions around those principles would make sense for the proposals template and when evaluating them.

However, I think we will have to accept that we don't all have the same prioritization approach, and that any vendor might have reasons for opposing a proposal that they can't be entirely transparent about. But we might still be able to move in the direction of a shared prioritization lens, without getting all the way there.

**Comment by foolip** [comment]
Attempted summary of our takeaways:
- The proposal/sub-proposal structure didn't work great, created some unnecessary problems. In the absence of this structure, do we need a second pass to group things, possibly drop things?
- Evaluating proposals is harder if we don't agree on what the goals are. Part of it is making sure that rationales are given. Some implicit goals never stated. Spend a bit of time in planning agreeing (more) on goals and evaluation criteria.
- We didn't stick to our deadlines, and some things were rushed while some things took a long time. Draw up a timeline in the beginning and stick to it.

**Comment by gsnedders** [comment]
I guess one process question is whether this is all being handled by the Interop team or if any of this is going back to the Core team, which I guess would be the latter if we want to amend the RFC to clarify any of t he above?

**Comment by foolip** [comment]
Also discussed today:

Do we want a clear call for public proposals? Do we want to seek input (probably not voting) from the public?
